language: node_js
node_js:
  - '5'
  - ‘4’

# échoue dès qu'une erreur intervient
matrix:
  fast_finish: true

# met en cache node_modules, à noter que dans ce genre d’utilisation pour des
# bibliothèques open source consommées via npm, il ne faudra pas oublier
# npm prune utilisé ci-après, histoire de ne pas lancer des tests avec
# des paquets encore en cache mais non présents dans le package.json
cache:
  directories:
    - node_modules

before_install:
  - npm prune

# ici on peut mettre des commandes à utiliser avec le script
before_script:
  # certains runners comme karma, testem ou testling peuvent avoir
  # besoin d'un écran pour fonctionner, voici l'astuce :)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# si on veut utiliser autre chose que la commande par défaut
#script: npm run test-with-coverage
script: npm run test

# voici un exemple de ce que l’on peut faire après les tests :
# on peut lancer une tâche qui va envoyer les informations de
# pourcentage de couverture de code à un service tiers.
# (eg: http://coveralls.io/, https://codecov.io/)
#after_success: 'npm run coverage'

# partie intéressante : ici on ne va déployer que les commits sur la
# branche master uniquement pour une version de node
# (car sinon on déploierait plusieurs fois…)
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
    node: '5'

# variables d'env
env:
  global:
  - NODE_ENV=production
  - secure: QRtUwUkqB9XWPUtmgStf2YoTLzC0dTVq2qDyJd+mHST22PbGVAIbdDNPm97CVjPU7ZjiHRNpPr9hW/8jd+M2InXtHX7EJ0QQK8lyoTChyvuQyz1a98Mtts2km6kktBy3PIXdwd1k3P2pVhwqLz82ZssbI0hFKSkkDacfA5BNHPB2v8RrYEmqaESQ13zJJKPAubQG+YGxbNIo2NhcFWFjUdaCDMnjcwWP+VBIh8jSdrtqzjIyom7VZjCdhG4r96HpwdDMb8D1vzIRi8GAckHHLPVBUfsXgVpK3MLpGfWPeUS/1XqzhWzU7X7M2y6k0Ptyv81h2zZ/xy4/cbIGtdMfv4/SiXhOo2JxHM3bYN/zKHwGnnJ3hoUvH+hMKqAvMQZJjiFZ2Xrw+6LL2aP+7bqeUKGzT9PzAA3wDDp1IPn2Fghc/hgm/0CwPuJ5PhlstEmgxy4mD3CPg6ZLfPHnHHkSbRIITxsCtcfArt4LfWloEPSSRiEYUkrY8HteLg0/zuNiIlLr/uz5pxL46Jy4OAY8h3naksVVt850oHbufhkW/3UlOOH3VBrHGyFXyR3G53m3irpcG6EHi+eqdoQsBi6ZtAt41HzvQk72W5/hCT24VHn/yyZY6/TdRRpCFyXwVDcg3thMiPw6iMkJXsuNyAw7e/kv6DkGVmXbk/HzcBW9q70=
  - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/nansou13/cra2.git